import React,{useEffect,useMemo,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {createClient} from '@supabase/supabase-js'
import {Plus,Check,Trash2,ShoppingCart,Users,Settings,LogOut,RefreshCw,ChevronDown,ChevronUp} from 'lucide-react'
import './style.css'

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY)
const presets=[['🍞','Ekmek','Temel'],['🥚','Yumurta','Kahvaltı'],['🥛','Süt','Süt ürünleri'],['🥤','Kefir','Süt ürünleri'],['🧀','Peynir','Süt ürünleri'],['🫒','Zeytinyağı','Kiler'],['🍅','Domates','Manav'],['🥒','Salatalık','Manav'],['🍌','Muz','Manav'],['🍎','Elma','Manav'],['🍗','Tavuk','Et'],['🥩','Et','Et'],['🍚','Pirinç','Kiler'],['🍝','Makarna','Kiler'],['🧻','Tuvalet kağıdı','Ev'],['🧴','Deterjan','Ev'],['🍼','Bebek ürünü','Bebek']]
const cats=['Hepsi','Kahvaltı','Süt ürünleri','Manav','Et','Kiler','Ev','Bebek','Diğer']

function App(){
 const [session,setSession]=useState(null),[items,setItems]=useState([]),[house,setHouse]=useState(null),[members,setMembers]=useState([]),[loading,setLoading]=useState(true),[filter,setFilter]=useState('Hepsi'),[showBought,setShowBought]=useState(false),[newItem,setNewItem]=useState(''),[qty,setQty]=useState(''),[cat,setCat]=useState('Diğer'),[icon,setIcon]=useState('🛒'),[name,setName]=useState(localStorage.getItem('ev_name')||''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authMode,setAuthMode]=useState('login'),[msg,setMsg]=useState(''),[addOpen,setAddOpen]=useState(false),[code,setCode]=useState('')
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe()},[])
 useEffect(()=>{if(session) loadHouse(); else {setLoading(false)}},[session])
 useEffect(()=>{if(new URLSearchParams(location.search).get('add')==='1') setAddOpen(true)},[])
 async function loadHouse(){setLoading(true); let {data:m}=await supabase.from('household_members').select('household_id,name').eq('user_id',session.user.id).limit(1).maybeSingle(); if(m){let {data:h}=await supabase.from('households').select('*').eq('id',m.household_id).single(); setHouse(h); let {data:ms}=await supabase.from('household_members').select('*').eq('household_id',m.household_id).order('created_at'); setMembers(ms||[]); await loadItems(m.household_id); subscribe(m.household_id)} setLoading(false)}
 async function loadItems(hid){let {data}=await supabase.from('shopping_items').select('*').eq('household_id',hid).order('is_bought').order('created_at',{ascending:false});setItems(data||[])}
 function subscribe(hid){supabase.channel('shopping-'+hid).on('postgres_changes',{event:'*',schema:'public',table:'shopping_items',filter:`household_id=eq.${hid}`},()=>loadItems(hid)).subscribe()}
 async function addItem(preset){const n=preset?.[1]||newItem.trim();if(!n||!house)return; await supabase.from('shopping_items').insert({household_id:house.id,name:n,quantity:preset?.[3]||qty,icon:preset?.[0]||icon,category:preset?.[2]||cat,added_by:session.user.id});setNewItem('');setQty('');setAddOpen(false)}
 async function toggle(i){await supabase.from('shopping_items').update({is_bought:!i.is_bought,bought_at:!i.is_bought?new Date().toISOString():null}).eq('id',i.id)}
 async function remove(i){await supabase.from('shopping_items').delete().eq('id',i.id)}
 async function auth(){setMsg(''); if(authMode==='signup'){let r=await supabase.auth.signUp({email,password}); if(r.error)setMsg(r.error.message);else setMsg('Hesap oluşturuldu. E-postanı doğruladıysan giriş yapabilirsin.')}else{let r=await supabase.auth.signInWithPassword({email,password});if(r.error)setMsg(r.error.message)}}
 async function createHome(){let r=await supabase.rpc('create_household',{p_name:'Bizim Ev',p_member_name:name||'Üye'});if(r.error)setMsg(r.error.message);else {setCode(r.data?.[0]?.invite_code||'');await loadHouse()}}
 async function joinHome(){let r=await supabase.rpc('join_household',{p_code:code,p_name:name||'Üye'});if(r.error)setMsg(r.error.message);else await loadHouse()}
 const visible=useMemo(()=>items.filter(i=>(filter==='Hepsi'||i.category===filter)&&(showBought||!i.is_bought)),[items,filter,showBought]);
 if(!session)return <Auth email={email} setEmail={setEmail} password={password} setPassword={setPassword} mode={authMode} setMode={setAuthMode} onAuth={auth} msg={msg}/>;
 if(loading)return <div className="center">Yükleniyor…</div>
 if(!house)return <div className="center"><div className="card setup"><div className="big">🛒</div><h1>Ev Listesi</h1><p>Üç kişilik ortak listenizi kur.</p><input placeholder="Adın" value={name} onChange={e=>setName(e.target.value)}/><button onClick={createHome}>Yeni ev oluştur</button><div className="or">veya</div><input placeholder="Ev kodu (örn. A1B2C3)" value={code} onChange={e=>setCode(e.target.value)}/><button className="secondary" onClick={joinHome}>Mevcut eve katıl</button>{msg&&<p className="error">{msg}</p>}<button className="link" onClick={()=>supabase.auth.signOut()}>Çıkış yap</button></div></div>
 return <div className="app"><header><div><div className="eyebrow">BUGÜN</div><h1>Ev alışverişi</h1><div className="sub">{items.filter(x=>!x.is_bought).length} ürün bekliyor · {members.length} kişi</div></div><div className="header-actions"><button className="iconbtn" onClick={()=>loadItems(house.id)} title="Yenile"><RefreshCw size={19}/></button><button className="iconbtn" onClick={()=>setShowBought(!showBought)}><Check size={19}/></button></div></header>
 <div className="chips">{cats.map(c=><button key={c} className={filter===c?'chip active':'chip'} onClick={()=>setFilter(c)}>{c}</button>)}</div>
 <main>{visible.length===0?<div className="empty"><ShoppingCart size={34}/><h2>Liste temiz 🎉</h2><p>Eksilen bir şeyi hemen ekle.</p></div>:<div className="list">{visible.map(i=><div className={'item '+(i.is_bought?'bought':'')} key={i.id}><button className="check" onClick={()=>toggle(i)}>{i.is_bought&&<Check size={18}/>}</button><span className="emoji">{i.icon}</span><div className="itemtext"><strong>{i.name}</strong><small>{i.quantity||' '} {i.quantity&&'·'} {i.category}</small></div><button className="delete" onClick={()=>remove(i)}><Trash2 size={17}/></button></div>)}</div>}</main>
 <button className="fab" onClick={()=>setAddOpen(true)}><Plus size={25}/> <span>Ürün ekle</span></button>
 <section className="bottomcard"><div><b>{house.name}</b><small> Ev kodu: <strong>{house.invite_code}</strong></small></div><div className="members">{members.map((m,n)=><span title={m.name} key={m.user_id}>{(m.name||'Ü').slice(0,1).toUpperCase()}</span>)}</div></section>
 {addOpen&&<div className="overlay" onClick={()=>setAddOpen(false)}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="sheethead"><h2>Listeye ekle</h2><button className="iconbtn" onClick={()=>setAddOpen(false)}>×</button></div><div className="quick">{presets.map(p=><button key={p[1]} onClick={()=>addItem(p)}><span>{p[0]}</span>{p[1]}</button>)}</div><div className="custom"><input autoFocus placeholder="Başka bir ürün…" value={newItem} onChange={e=>setNewItem(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addItem()}/><input className="qty" placeholder="Adet" value={qty} onChange={e=>setQty(e.target.value)}/><select value={cat} onChange={e=>setCat(e.target.value)}>{cats.slice(1).map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>addItem()}>Ekle</button></div></div></div>}
 </div>
}
function Auth({email,setEmail,password,setPassword,mode,setMode,onAuth,msg}){return <div className="center"><div className="card setup"><div className="big">🛒</div><h1>Ev Listesi</h1><p>Üç kişinin ortak kullanacağı alışveriş listesi.</p><input type="email" placeholder="E-posta" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Şifre" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={onAuth}>{mode==='login'?'Giriş yap':'Hesap oluştur'}</button>{msg&&<p className="error">{msg}</p>}<button className="link" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'İlk kez kullanıyorum':'Zaten hesabım var'}</button></div></div>}
createRoot(document.getElementById('root')).render(<App/>)
